apps/cv/urls.py
from django.urls import path

from .views import download_cv_pdf


urlpatterns = [
    path('<int:pk>/pdf', download_cv_pdf,  name='cv-pdf'),
]

cookbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('email/', include('email_messages.urls', namespace='email_messages')),

    path('quotes/', include('quotes.urls', namespace='quote')),
    path('bulletins/', include('bulletin_board.urls', namespace='bulletins')),

    path('movies/', include('movies.urls')),

    path('cv/', include('cv.urls')),
    path('search/', include('haystack.urls')),
]

apps/cv/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class CurriculumVitae(models.Model):
    class Meta:
        verbose_name = _("Curriculum Vitae")
        verbose_name_plural = _("Curricula Vitarum")

    first_name = models.CharField(_("First name"), max_length=40)
    last_name = models.CharField(_("Last name"), max_length=40)
    email = models.EmailField(_("Email"))

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Experience(models.Model):
    class Meta:
        ordering = ("-from_date",)
        verbose_name = _("Experience")
        verbose_name_plural = _("Experiences")

    cv = models.ForeignKey(CurriculumVitae,
                           on_delete=models.CASCADE)
    from_date = models.DateField(_("From"))
    till_date = models.DateField(_("Till"), null=True, blank=True)
    company = models.CharField(_("Company"), max_length=100)
    position = models.CharField(_("Position"), max_length=100)
    skills = models.TextField(_("Skills gained"), blank=True)

    def __str__(self):
        date_format = "%m/%Y"
        till = (f"{self.till_date:{date_format}}"
                if self.till_date
                else _("present"))
        start = f"{self.from_date:{date_format}}"
        return f"{start}-{till} {self.position} at {self.company}"

apps/cv/views.py
import os

from django.conf import settings
from django.http import HttpResponse, HttpResponseServerError
from django.shortcuts import get_object_or_404, render_to_response
from django.template.loader import render_to_string
from django.utils.text import slugify
from xhtml2pdf import pisa

from .models import CurriculumVitae


def font_patch():
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.pdfbase import pdfmetrics
    from xhtml2pdf.default import DEFAULT_FONT
    pdfmetrics.registerFont(TTFont('yh', '{}/font/msyh.ttf'.format(settings.STATICFILES_DIRS[0])))
    DEFAULT_FONT['helvetica'] = 'yh'


def link_callback(uri, rel):
    # convert URIs to absolute system paths
    if uri.startswith(settings.MEDIA_URL):
        path = os.path.join(settings.MEDIA_ROOT,
                            uri.replace(settings.MEDIA_URL, ""))
    elif uri.startswith(settings.STATIC_URL):
        path = os.path.join(settings.STATIC_ROOT,
                            uri.replace(settings.STATIC_URL, ""))
    else:
        # handle absolute uri (i.e., "http://my.tld/a.png")
        return uri

    # make sure that the local file exists
    if not os.path.isfile(path):
        raise Exception(
            "Media URI must start with "
            f"'{settings.MEDIA_URL}' or '{settings.STATIC_URL}'")

    return path


def download_cv_pdf(request, pk):
    cv = get_object_or_404(CurriculumVitae, pk=pk)

    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = \
        f"attachment; filename='{slugify(cv, True)}.pdf'"

    html = render_to_string("cv/cv_pdf.html", {"cv": cv})
    font_patch()
    status = pisa.CreatePDF(html,
                            dest=response,
                            link_callback=link_callback)

    if status.err:
        return HttpResponse("The PDF could not be generated")

    return response

templates/cv/cv_pdf.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{{ cv }}</title>
    <style>
        @page {
            size: a4 portrait;
            margin: 2.5cm 1.5cm;

            @frame footer_frame {
                -pdf-frame-content: footer_content;
                bottom: 0;
                margin-left: 0;
                margin-right: 0;
                height: 1cm;
            }
        }

        #footer_content {
            color: #666;
            font-size: 10pt;
            text-align: center;
        }

        h1 { text-align: center; }
        th, td { vertical-align: top; }
        /* ... additional styles here ... */
    </style>
</head>
<body>
<div>
    <h1>Curriculum Vitae for {{ cv }}</h1>

    <table><tr>
        <td>
            <h2>Contact Information</h2>
            <p><b>Email:</b> {{ cv.email }}</p>
        </td>
        <td align="right">
            <img src="{% static 'site/img/smiley.jpg' %}"
                 width="100" height="100" />
        </td>
    </tr></table>

    <h2>Experience地方</h2>

    {% for experience in cv.experience_set.all %}
        <h3>{{ experience.position }} at {{ experience.company }}</h3>
        <p><b>
            {{ experience.from_date|date:"F Y" }} -
            {{ experience.till_date|date:"F Y"|default:"present" }}
        </b></p>
        <p>
            <b>Skills gained</b><br>
            {{ experience.skills|linebreaksbr }}
        </p>
    {% endfor %}
</div>
<pdf:nextpage>
<div>
    This is an empty page to make a paper plane.
</div>
<div id="footer_content">
    Document generated at {% now "Y-m-d" %} |
    Page <pdf:pagenumber> of <pdf:pagecount>
    | Smiley obtained from clipartextras.com
</div>
</body>
</html>